plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kaoyan.app'
    compileSdk 35

    defaultConfig {
        applicationId "com.kaoyan.app"
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName "3.0"
    }

    signingConfigs {
        release {
            storeFile file('../release.keystore')
            storePassword 'kaoyan123'
            keyAlias 'kaoyan'
            keyPassword 'kaoyan123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
